### ISSUE TITLE
Handle 'dest' property in files config.

### ISSUE THREAD

**Issue by tjuszczyk** [mrkelly/grunt-maven-deploy#2]
During deploy procedure zip artifact is created in main directory.
Shouldn't it be created in directory pointed by 'dest' property of 'files' config:

ex. 

```
'widgets-release':{
    options: {
        url: settings.releaseRepository,
        repositoryId: settings.releaseRepositoryID,
        goal: "install" //install
    },
    files: [{expand: true, cwd: 'dist/', src: ['**'], dest: 'maven/'}]
}
```

Artifact  should be created in maven dir.

**Comment by qualidafial** [comment]
I think you're looking for the options.file parameter. I'm away from my
computer at the moment, but I believe that dest controls the path where
files are placed inside the archive.

**Comment by mrkelly** [comment]
@qualidafial is right, use options.file to specify the destination of the archive and it's file name.

**Comment by tjuszczyk** [comment]
Thanks, you're right 'files' property should be used.
Can you advise me thou, how easily I can reuse default file name: 
`options.file = options.artifactId + '-' + options.version + '.' + options.packaging`
but to have this file in some dest folder, let say /maven

**Comment by qualidafial** [comment]
Something like:

```
options: {
  file: "maven/<%= options.artifactId %>-<%= options.version %>.<%= options.packaging %>"
}
```

I might be open to adding an option e.g. options.archiveDest to make this simpler.

**Comment by tjuszczyk** [comment]
AFAIK it's not so simple to use options in a grunt templating engine: `<%= options %>` does not work. On a current task object (grunt.task.current) options is a function and we cannot use it in <%= ....
It would be nice to have to have such a property in a configuration ex. artifactDirectory

**Comment by qualidafial** [comment]
Make those <%= maven_deploy.options.whatever %>

**Comment by seglo** [comment]
I recently tried doing something similar and thought I'd share my solution.  As @qualidafial already mentioned you can refer to the options using maven_deploy.options, but the version isn't populated when the grunt templating engine runs.  I also have to hardcode -SNAPSHOT into the option.file if I want it to use that convention.

``` javascript
'maven_deploy': {
      options: {
        groupId: 'group',
        artifactId: '<%= pkg.name %>',        
        packaging: 'war',
        version: '<%= pkg.version %>'
      },
      'snapshot_deploy': {
        files: [{
          expand: true,
          cwd: 'dist',
          src: ['**'],
          dest: ''
        }],

        options: {
          file: 'target/<%= maven_deploy.options.artifactId %>-<%= maven_deploy.options.version %>-SNAPSHOT.<%= maven_deploy.options.packaging %>'
        }
      }
   }
```

**Comment by qualidafial** [comment]
Workaround:

``` javascript
    options: {
      file: 'target/<%= maven_deploy.options.artifactId %>-<%= maven_deploy.options.version %><%= maven_deploy.options.snapshot ? "-SNAPSHOT" : "" %>.<%= maven_deploy.options.packaging %>'
    }
```
